version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  customers-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-customers
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8001:8080"
    environment:
      - RabbitMQ__HostName=rabbitmq

  creditproposals-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-creditproposals
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RabbitMQ__HostName=rabbitmq

  creditcards-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-creditcards
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RabbitMQ__HostName=rabbitmq